# Backend configuration for the CMS. Any backend will also support working with your repository locally by choosing it at the login screen.
backend:
  # The backend to use
  name: github
  # The branch to commit to. Cannot be protected
  branch: main
  # The repository from your backend to work from
  repo: snugug/saddle-river-deli
  # The domain your site is hosted on, without protocol
  site_domain: saddlerivergourmet.com
  # The full base URL of your site, including protocol and subpath
  base_url: https://www.saddlerivergourmet.com/
  # The OAuth route to use for authentication. GitHub requires a backend server, or you can authenticate with a Personal Access Token directly in browser
  auth_endpoint: oauth

# The source URL to store CMS uploaded media
media_folder: public/media
# The folder where media will be served from. If your site is served from a subpath, it must be included here.
public_folder: /media

# Content collections
collections:
  - label: Menus
    name: menu
    folder: src/content/menu
    create: true
    sortable_fields:
      - title
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        required: false
      - label: Labeling
        hint: How regular and large sizes should be labeled
        name: labeling
        widget: object
        summary: 'Regular: {{fields.regular}} / Large: {{fields.large}}'
        required: false
        fields:
          - label: Regular
            name: regular
            widget: string
            required: false
          - label: Large
            name: large
            widget: string
            required: false
      - label: Items
        name: items
        widget: list
        fields:
          - label: Name
            name: name
            widget: string
          - label: Regular Cost
            name: regular
            widget: number
            min: 0
            step: .01
            value_type: float
            required: false
          - label: Large Cost
            name: large
            widget: number
            min: 0
            step: .01
            value_type: float
            required: false
  - label: Menu Boards
    name: menuboard
    folder: src/content/menuboard
    create: true
    sortable_fields:
      - weight
    fields:
      - label: Title
        name: title
      - label: Weight
        name: weight
        widget: number
        value_type: int
        default: 0
      - label: Board
        name: board
        widget: list
        field:
          label: Menu Board
          name: menu
          widget: relation
          collection: menu
          value_field: '{{slug}}'
          display_fields:
            - title
          search_fields:
            - title
  - label: Catering Menus
    name: catering
    folder: src/content/catering
    create: true
    sortable_fields:
      - weight
    fields:
      - label: Title
        name: title
      - label: Description
        name: description
        widget: text
        required: false
      - label: Options
        name: options
        widget: list
        field:
          label: Item
          name: item
          widget: object
          fields:
            - label: Title
              name: title
            - label: Description
              name: description
              widget: text
              required: false
            - label: Price
              name: price
              widget: object
              fields:
                - label: Servings
                  name: servings
                  widget: list
                  field:
                    label: Serving
                    name: serving
                    widget: object
                    summary: '{{fields.title}}: ${{fields.cost}}'
                    fields:
                      - label: Price
                        name: cost
                        widget: number
                        min: 0
                        step: .01
                        value_type: float
                      - label: Serving Size
                        name: title
                        default: per person
                      - label: Is a platter
                        name: platter
                        widget: boolean
                        hint: This will display the serving size as a title instead of as a cost per serving size
                        required: false
                - label: Minimum
                  name: string
                  required: false
            - label: Extras
              name: extras
              widget: list
              required: false
              field:
                label: Extra
                name: extra
                widget: object
                summary: '{{fields.title}}: ${{fields.cost}}'
                fields:
                  - label: Description
                    name: title
                  - label: Price
                    name: cost
                    widget: number
                    min: 0
                    step: .01
                    value_type: float
      - label: Weight
        name: weight
        widget: number
        value_type: int
        default: 0
